apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-app-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-app-3
    app.kubernetes.io/part-of: my-app-3
  name: my-app-3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-app-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-app-3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/nmukherj-tenant/my-app-3/my-app-3@sha256:0f4351e3303a4826cf82c47606307c16054a3ba2f19d7f4430fcb2d441be4a65
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
